### ISSUE TITLE
ownership inquiry

### ISSUE THREAD

**Issue by dpep** [ko1/rspec-debug#2]
Hi Koichi,

A friend and I are working on rspec debugging tools and found your [rspec-debug gem](https://rubygems.org/gems/rspec-debug) and this repo.  It is a great idea to automatically invoke the debugger if a spec fails and neat to see how you implemented it!

I noticed this repo has not changed for a few years and was wondering if you would be open to contributions?  Or would you be willing to grant me ownership [in RubyGems](https://rubygems.org/gems/rspec-debug/owners) so that we could continue working on making rspec debugging easier?

Thanks for your contributions and consideration,
-Daniel

**Comment by ko1** [comment]
open to contribution. But this library is enough small and you can copy it on your project.

**Comment by dpep** [comment]
cool, happy to keep this library small.  I'll explore other options
